# Generated by Django 3.1.2 on 2020-10-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_auto_20201023_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.FilePathField(path='storefront/static/img/'),
        ),
    ]
