# Generated by Django 3.1.2 on 2020-10-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_auto_20201023_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='category',
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.FilePathField(),
        ),
        migrations.AddField(
            model_name='store',
            name='categories',
            field=models.ManyToManyField(related_name='item', to='storefront.Category'),
        ),
    ]
