# Generated by Django 3.1.2 on 2020-10-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0008_auto_20201026_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.FilePathField(path='static/img/'),
        ),
    ]
