# Generated by Django 3.1.2 on 2020-10-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0012_auto_20201026_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.FilePathField(path='/img'),
        ),
    ]
