# Generated by Django 3.1.2 on 2020-11-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0013_auto_20201026_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.FilePathField(path='storefront/static/img'),
        ),
    ]
