# Generated by Django 3.1.2 on 2020-11-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0014_auto_20201102_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.FilePathField(path='/img/'),
        ),
    ]
